db: offline_all_magnitudes_corrected
signal_type: vel
sacs_db: microsismicidad
seeds:
- 1111
- 9992
preprocess_config:
  response: VEL
  frame_length: 4
  frame_shift: 2
  window_limit:
  - 20
  - 120
  filter:
  - highpass
  - 1
  norm_energy: false
  square_fft: true
  log_scale: false
model_config:
  criterion_selection: mae
  optimizer_selection: adam
  learning_rate: 0.0001
  device: cuda
  use_splited_mlp: true
  num_channels: 3
  input_dim: 130
  output_dim: 1
  u_dim: 42
  n2_dim: 42
  nhead: 1
  act_sel: gelu
  ln_eps: 1.0e-05
  channel_hidden: 50
  frame_hidden: 50
  gru_hidden: 20
  dropout: 0.1
  shared_channel_mlp: true
  use_activation: true
train_config:
  epochs: 300
  patience: 50
  delta: 0.001
  batch_size: 4
  num_workers: 4
  save_model: true
