db: bdd_paper_wout_errors
signal_type: vel
sacs_db: sac_manual_resegmented
device: cuda
seeds:
- 1111
- 2222
- 3333
- 4444
- 9992
preprocess_config:
  response: VEL
  frame_length: 4
  frame_shift: 2
  window_limit:
  - 20
  - 120
  filter:
  - highpass
  - 1
  norm_energy: false
  square_fft: true
  mean_temporal_features: false
  NEW_concat_temporal_features: true
model_config:
  n_bins: 390
  num_channels: 3
  u_dim: 42
  n2_dim: 42
  out_dim: 1
  mha_heads: 1
  act_sel: gelu
  ln_eps: 1.0e-05
  channel_hidden: 50
  frame_hidden: 50
  dropout: 0.1
  shared_channel_mlp: true
  use_activation: true
  use_positional_encoding: true
  positional_encoding_type: learned
  mean_temporal_features: true
  temporal_processing_module: transformer
  n_temporal_processing_modules: 1
  use_cnn_embedding: true
  cnn_embedding_layers:
  - input_dim: 390
    out_channels: 500
    kernel_size: 3
    padding: 1
    stride: 1
    padding_mode: replicate
    max_pool_kernel_size: 2
    max_pool_stride: 2
    pool_type: max
train_config:
  epochs: 1000
  patience: 50
  delta: 0.1
  batch_size: 4
  num_workers: 0
  criterion_selection: mae
  optimizer_selection: adam
  learning_rate: 0.0001
  save_model: true
